Code formatting with forge
equilibria-xyz/perennial-v2 pull request #482
Opened 2024-10-22 13:01 UTC by prateekdefi

2024-10-22 14:44 UTC, EdNoepel requested changes
Please update the README with `forge` installation instructions.

2024-10-22 15:11 UTC, EdNoepel commented on packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
> +
This is a good example of something which cannot be maintained when using an auto-formatting tool.  Is implementing an auto-format solution worth the tradeoff of forfeiting our ability to align comments and parameters for readability?

2024-10-23 06:23 UTC, prateekdefi commented on packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
> +
I agree that auto formatting is not as precise as manual formatting but I think auto formatting is better for following reasons:
- manual formatting is time consuming and human error prone. Adds consistency throughout code.
- code comments help with readability and it would be better if the comments are aligned but it's not that important and can be sacrificed as per me.

2024-10-24 07:40 UTC, kbrizzle commented on packages/perennial/contracts/types/RiskParameter.sol
> +            UFixed6.wrap(uint256(slot0 << (256 - 24)) >> (256 - 24)),
Yeah losing the manual formatting here is not ideal either -- I think we should have a discussion on when to use the auto-formatter. It seems like our solidity at the very least is very out of sync with what `forge fmt` generates, so I'm not sure it makes sense to make this large of a change at this point.

2024-10-25 05:03 UTC, prateekdefi commented on packages/perennial/contracts/types/RiskParameter.sol
> +            UFixed6.wrap(uint256(slot0 << (256 - 24)) >> (256 - 24)),
What if we keep a combination of manual and auto formatting. We cannot skip files in forge but we can skip in prettier. @kbrizzle

2024-10-25 05:04 UTC, prateekdefi commented on packages/perennial/contracts/types/RiskParameter.sol
> +            UFixed6.wrap(uint256(slot0 << (256 - 24)) >> (256 - 24)),
we can skip files like the `RiskParameter.sol` where manual formatting is required.

2024-10-29 14:03 UTC, prateekdefi commented
In team meeting decided to not go with auto formatting for now.

2024-10-29 14:03 UTC, closed without merging